### ISSUE TITLE
[artwork] add filters to view artwork by artform

### ISSUE THREAD

**Issue by roadlittledawn** [roadlittledawn/kevincmaginnis#30]
## Summary

We want to change home page so a user can filter the slides by artform (painting, sculpture, installation, etc

## Outstanding Qs
- button design
- should be same page, not dedicated page

## Acceptance criteria
- [ ] buttons that when clicked update the slide show for only slides with selected artform
- [ ] add video support for vids in kevin's new AWS account

## Helpful links

**Comment by kevincmaginnis** [comment]
- Change "Artwork", "Bio", "Contact", and "CV" to "Installation", "Sculpture", "Painting", "CV", "Bio", "Contact" in that order.

**Comment by kevincmaginnis** [comment]
- Under "Installation" place Spun video on page one. See attached image.
![IMG_0893](https://github.com/roadlittledawn/kevincmaginnis/assets/114541284/080cab63-295f-4da8-b828-0adf5760dc79)

**Comment by kevincmaginnis** [comment]
- Under "Installation" place Suburban video on page 11.

**Comment by kevincmaginnis** [comment]
- Under "Installation" follow sequence of pages as as shown in attached images.
![IMG_0895](https://github.com/roadlittledawn/kevincmaginnis/assets/114541284/9552189f-73d2-4f50-9bc0-dd5d35f5f654)
![IMG_0894](https://github.com/roadlittledawn/kevincmaginnis/assets/114541284/0c4710d2-39fa-4a0b-be2b-c2f5436048a5)
![IMG_0896 (1)](https://github.com/roadlittledawn/kevincmaginnis/assets/114541284/2620ef65-2e7e-4719-b729-72273df9d51e)

**Comment by kevincmaginnis** [comment]
Under "Sculptures" add
![IMG_0897](https://github.com/roadlittledawn/kevincmaginnis/assets/114541284/3b717182-2593-4a53-be1d-cb8679f1e0ed)
 new detail image for Close Tightly on page 28 (photo to come). Delete the two Fence detail pages between pages 29 and 30. Follow sequence of pages 23 through 30 as shown.

**Comment by kevincmaginnis** [comment]
- Under "Paintings" follow sequence of pages 31 through 49 as shown.

![IMG_0898](https://github.com/roadlittledawn/kevincmaginnis/assets/114541284/bac0c0cd-3f5d-44a3-baba-b081260449ac)

- Add dates to 23-6-F (2023) page 31, 23-1-E (2023) page 32, 23-10-H (2023) page33, 22-5-B (2022) page 34.
- Delete 23-6-G as indicated.

![IMG_0899](https://github.com/roadlittledawn/kevincmaginnis/assets/114541284/32eefe24-19c9-4fc4-a670-a3db76f002b0)

- Correct typo on page 45 and 46 from "photo transfers on campus" to "photo transfers on canvas"

**Comment by kevincmaginnis** [comment]
- "CV", "Bio", and "Contact" are the same except for the order as indicated.
